name: Build and test examples

on:
  schedule:
    - cron: '0 0 * * *' # run at midnight every day
  workflow_dispatch:
    inputs:
      ref:
        description: "Branch/ref (default dev branch)"
        required: true
        default: 'dev' # checkout dev branch by default, not main

jobs:
  build-and-test-rust-examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.ref }}

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Debug 1
        run: |
          jq --help

      - name: Debug 2
        run: |
          echo $GITHUB_JOB

      - name: Get current date
        run: echo "CURRENT_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      
      - name: Cache cargo
        uses: actions/cache@v2.1.4
        with:
          # https://doc.rust-lang.org/cargo/guide/cargo-home.html#caching-the-cargo-home-in-ci
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          # Add date to the cache to keep it up to date
          key: ubuntu-latest-cargo-${{ github.job }}-${{ hashFiles('**/Cargo.toml') }}-${{ env.CURRENT_DATE }}
          # Restore from outdated cache for speed
          restore-keys: |
            ubuntu-latest-cargo-${{ github.job }}-${{ hashFiles('**/Cargo.toml') }}-
            ubuntu-latest-cargo-${{ github.job }}-
            ubuntu-latest-cargo-

      - name: Cache build target
        uses: actions/cache@v2.1.4
        with:
          path: target
          # Add date to the cache to keep it up to date
          key: ubuntu-latest-target-${{ github.job }}-${{ hashFiles('**/Cargo.toml') }}-${{ env.CURRENT_DATE }}
          # Restore from outdated cache for speed
          restore-keys: |
            ubuntu-latest-target-${{ github.job }}-${{ hashFiles('**/Cargo.toml') }}-
            ubuntu-latest-target-${{ github.job }}-
            ubuntu-latest-target-

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --examples --verbose

      - name: Run Rust examples
        working-directory: examples
        run: |
          cargo read-manifest | for entry in $(python3 -c "import sys, json; print(' '.join(list(map(lambda x: x['name'], json.load(sys.stdin)['targets']))))"); do cargo run --example "$entry"; done
  
  build-and-test-wasm-examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.ref }}

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 15.x

      - name: Install txm # for running README.md examples https://github.com/anko/txm
        run: yarn global add txm

      - name: Install wasm-pack
        run: yarn global add wasm-pack

      - name: Install JS dependencies
        run: yarn
        working-directory: bindings/wasm

      - name: Build Wasm bindings
        run: yarn build
        working-directory: bindings/wasm

      - name: Test Wasm examples (node)
        run: yarn run test:node
        working-directory: bindings/wasm

      - name: Test Wasm examples (browser)
        run: yarn run test:browser
        working-directory: bindings/wasm

      - name: Test Wasm README.md examples
        run: yarn run test:readme
        working-directory: bindings/wasm
